### ISSUE TITLE
Running this code on python 2.7 gives a syntax error

### ISSUE THREAD

**Issue by AbanoubMamdouh** [SsaRu/voc-annotation-to-yolo-format#11]
Hello,
Thank you very much for the effot you put into this code but I tried to run this code on python 2.7 so I wrote the command: python example.py --datasets VOC --img_path ~/VOC/Images/ --label ~/VOC/Annotations/ --convert_output_path ~/VOC/YOLO/ --img_type ".jpg" --manipast_path ./ --cls_list_file ~/VOC/voc.names and got the following syntax error: 
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    from Format import VOC, COCO, UDACITY, KITTI, YOLO
  File "/home/abanoub/Desktop/convert2Yolo-master/Format.py", line 71
    print('\r%s|%s| %s%% (%s/%s)  %s' % (prefix, bar, percent, iteration, total, suffix), end = '\r')
                                                                                              ^
SyntaxError: invalid syntax

Do know what would be a solution to such a problem?
Cheers!

**Comment by ssaru** [comment]
this project code wrote python3.

would you execute code with python 3?
