### ISSUE TITLE
원하는 클래스만 저장

### ISSUE THREAD

**Issue by dxtruong** [SsaRu/voc-annotation-to-yolo-format#12]
안녕하세요.
좋은 코드를 올려주셔서 감사합니다.
제가 실행해봤는데 잘 되더라고요.

다만 긍금한 거 하나 있습니다.
제가 사실은 voc datasets의 있는 car, bus, motorbike 클래스에대한 image와 annotation를 따로 저장했습니다.
annotation를 yolo형식으로 바꿀때 3가지 car,bus, motorbike에대한만 나올 수 있도록  voc.names 파일을 "car,bus,motorbike" 3가지만 저정했는데 오류 떴더라고요.
그래서 voc.names파일을 그대로 사용하고 코드를 어떻게 수정해야되나요?

도와주셔서 너무 너무 감사합니다.

**Comment by ssaru** [comment]
안녕하세요~ 
해당 요구사항이 있기도 하고, 코드도 엉망이라 리팩토링 해야지 하면서 못건들이고 있는 중입니다.

제가 리팩토링을 조만간 진행하려고하는데, 

급하실거 같아서, 먼저 설명드리겠습니다.
먼저, 대부분의 처리는 `Format.py`을 통해서 이루어집니다.
voc dataset의 경우 `Format.py`에서 `VOC class` 내부에 이를 처리하는 로직들이 들어가 있구요.
`VOC class`의 `parse`라는 함수가 있을 겁니다. 

여기서 object name을 parsing하는 부분이 있을건데, 원하는 object name이 아닐 경우에 예외처리 로직을 넣어주시면 될 거 같습니다.

**Comment by dxtruong** [comment]
답장해주셔서 감사합니다.
제도 parse 함수를 건들어 봤는데 @ssaru 님 말씀하시대로 코딩 좀 복잡해서 대도체 못 했습니다.
저는 코딩 초보자라서요 ㅠㅠ
다른 방법 생각해서 실행했습니다.
그 방법은 :
1. 올려주신 코드 그대로 실행한후
2. YOLO folder에 있는 annotation file 는  멘 앞 line의 값은 [ 0~19] (20class 뜻) 보입니다.  
3. 간단한 .txt 파일 처리하는 코드해서  원하는 class만 남아 있고 나머지를 다 삭제합니다.
제 경우는 car, bus, motorbike의 값은  0,1,2이고 남은 값은 불필요해서 다 삭제했습니다.

결과가 원하는대로 나왔습니다.
^^ 
@ssaru 님의 코딩떡분에 문제 해결할 수 있어서 정말 고마웠습니다.
