### ISSUE TITLE
.git file is too big

### ISSUE THREAD

**Issue by lzane** [SsaRu/voc-annotation-to-yolo-format#2]
There are nearly 240MB inside `.git/objects`. Cloud you please clear them all otherwise we can't use `git clone` directly since it will download all include this giant file.

Thanks~

**Comment by ssaru** [comment]
Thanks for your attention, i was clean up repository history
Could you check my modification?
if you satisfied my modificated code Please close issue :)

Thanks!

**Comment by lzane** [comment]
Yes, Thanks for your script! it saves me lots of time.
