### ISSUE TITLE
A slight change needed in the convert2Yolo.py script

### ISSUE THREAD

**Issue by hakimka** [SsaRu/voc-annotation-to-yolo-format#3]
If for any reason an XML file would not have "object" entity, the script chokes at 
![image](https://user-images.githubusercontent.com/3639143/35303050-a7cc4c6a-005e-11e8-9beb-fe501a90ea0d.png)

I'd  suggest to close the xml"file before removing it from them "xml_path".  

Thanks.

**Comment by ssaru** [comment]
Hello, hakimka!

i was edit my code following your suggestion

plz check it !

Thanks!
