### ISSUE TITLE
A lot of path and file handling problems

### ISSUE THREAD

**Issue by cansik** [SsaRu/voc-annotation-to-yolo-format#4]
There are a lot of path problems in your code. For example you should combine the paths with a method, not just with the `+` operator.

And the output path for the text files is wrong in the [convert2Yolo.py](https://github.com/SsaRu/convert2Yolo/blob/master/convert2Yolo.py#L401). It should be:

```python
result_outpath = str(label_dir + xml_name[:-3] + "txt")
```

Or for example you are not just reading `.xml` files.

**Comment by ssaru** [comment]
thanks about your opinion
now im trying refactoring my code

if you have a solution would you send pull request for my project?

thanks :)
