### ISSUE TITLE
Example code outdated

### ISSUE THREAD

**Issue by raggot** [SsaRu/voc-annotation-to-yolo-format#5]
Hi,

I tried to copy paste the example code from your readme but I found out (from the error messages and help) that you renamed these arguments

--image_path became --img_path
--image_type became --img_type
--clas_list_file became --cls_list_file

I prepared a pull request but Git tells me I don't have access to your repo

**Comment by ssaru** [comment]
Hi! thanks about it!

would you following procedure?

1. fork my repository
2. some code modify
3. pull request

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by raggot** [comment]
It's literally 3 words to change, not worth it for this time but I'll do it if I end up making more important changes ;)
