### ISSUE TITLE
'ascii' codec can't encode character

### ISSUE THREAD

**Issue by memina** [SsaRu/voc-annotation-to-yolo-format#8]
Hi, 

First of all, thank you for making this script.

I downloaded the 2014 database from Coco's own site. I ran the script below. Process is starting but a character error message appears at  % 3 process.

So how can i resolve this problem ?

python3 example.py --datasets COCO --img_path /coco/images/train2014/ --label /coco/annotations/instances_train2014.json --convert_output_path ./ --img_type ".jpg" --manipast_path ../ --cls_list_file ../data/coco_15c.names

COCO Parsing Result : False, msg : ERROR : 'ascii' codec can't encode character '\u2588' in position 17: ordinal not in range(128), moreInfo : <class 'UnicodeEncodeError'>     Format.py       366

**Comment by ssaru** [comment]
Hi @memina 

i will check error

what your OS?

**Comment by memina** [comment]
@ssaru my os is Ubuntu

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

I trying to convert instances_train2014.json file that there is link at below.
https://vision.ece.vt.edu/mscoco/coco/annotations/

**Comment by memina** [comment]
I think problem is running with ssh. 
Now I'm trying again over the console, process came to 18% and continues.

Thanks

**Comment by ssaru** [comment]
@memina 
Ok! have a nice day :)

**Comment by memina** [comment]
@ssaru thank you but final is not good :(

After then %100 completed,  error message is;

YOLO Generating Result: False, msg: ERROR: 'potted plant' is not in list, moreInfo: <class 'ValueError'> Format.py 702

My coco_15c.names file doesn't already have a potted plant. why did he give this error?

[https://ibb.co/2dN8brF](url)

I want to training below objects using coco dataset. 

tie
bottle
cup
knife
spoon
banana
apple
orange
carrot
mouse
remote
cell phone
clock
scissors
toothbrush

**Comment by ssaru** [comment]
@memina 

in my guess, instances_train2014.json file have a label as pottedplant.

refer here https://github.com/pjreddie/darknet/blob/master/data/coco.names

would you wanna skip some label as didn't want?

**Comment by memina** [comment]
Yes, I would like to skip names other than the ones in my coco names file.

**Comment by ssaru** [comment]
ok i will update my code. until this week.

if you urgent you could add custom code from my code

you can solve this problem using `continue` keyword in my code

**Comment by memina** [comment]
Ok, thank you. I added below codes, and run as filtered.

with open('../data/coco_15c.names', 'r') as file:
            lnames = file.read().splitlines()
          

if cls not in lnames:
                    continue

**Comment by raynbowy23** [comment]
For anyone who is struggling with ascii issue, this is probably due to ssh, but if you use ssh, just replace '█' (full block) on line 56 in Format.py to any other character.

**Comment by winself** [comment]
@raynbowy23 THANK YOU!  Solve my problems.

**Comment by priteshgohil** [comment]
@raynbowy23 Thanks. Why don't we keep this issue open until author fix his code?
